apiVersion: apps/v1
kind: Deployment
metadata:
  name: coordinator
spec:
  replicas: 1
  selector:
    matchLabels:
      app: coordinator
  template:
    metadata:
      labels:
        app: coordinator
    spec:
      terminationGracePeriodSeconds: 120
      containers:
        - name: coordinator
          image: arturmkr/graceful-coordinator:latest
          ports:
            - containerPort: 8000
          env:
            - name: WORKER_URL
              value: "http://worker:8001"