apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: worker
  template:
    metadata:
      labels:
        app: worker
    spec:
      terminationGracePeriodSeconds: 120
      containers:
        - name: worker
          image: arturmkr/graceful-worker:latest
          ports:
            - containerPort: 8001
          env:
            - name: COORDINATOR_URL
              value: "http://coordinator:8000"